# Generated by Django 5.2.4 on 2025-07-10 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillsview',
            name='category',
            field=models.CharField(choices=[('Frontend Development', 'Frontend Development'), ('Tools & Technologies', 'Tools & Technologies')], default='', max_length=50),
            preserve_default=False,
        ),
    ]
