# Generated by Django 5.2.4 on 2025-07-24 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_website', '0002_skillsview_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeview',
            name='image',
        ),
        migrations.AddField(
            model_name='homeview',
            name='video',
            field=models.FileField(default='exit', upload_to='videos/'),
            preserve_default=False,
        ),
    ]
